from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# Not used, I need the instance to properly validate groups field
def groups_validator(value):
    pass
